#!/bin/sh

# Start/stop script for webcam driver

case "$1" in
    start)
	echo "Loading webcam driver"
	modprobe uvcvideo
	;;
    stop)
	echo "Unloading webcam driver"
	rmmod uvcvideo

	# Remove stale nodes
	rm -f /dev/uvcvideo
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0